//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASMXClient.ServiceReference1 {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReference1.WebServiceSoap")]
    public interface WebServiceSoap {
        
        // CODEGEN: Generating message contract since element name HelloWorldResult from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/HelloWorld", ReplyAction="*")]
        ASMXClient.ServiceReference1.HelloWorldResponse HelloWorld(ASMXClient.ServiceReference1.HelloWorldRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/HelloWorld", ReplyAction="*")]
        System.Threading.Tasks.Task<ASMXClient.ServiceReference1.HelloWorldResponse> HelloWorldAsync(ASMXClient.ServiceReference1.HelloWorldRequest request);
        
        // CODEGEN: Generating message contract since element name number1 from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Summ", ReplyAction="*")]
        ASMXClient.ServiceReference1.SummResponse Summ(ASMXClient.ServiceReference1.SummRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Summ", ReplyAction="*")]
        System.Threading.Tasks.Task<ASMXClient.ServiceReference1.SummResponse> SummAsync(ASMXClient.ServiceReference1.SummRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class HelloWorldRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="HelloWorld", Namespace="http://tempuri.org/", Order=0)]
        public ASMXClient.ServiceReference1.HelloWorldRequestBody Body;
        
        public HelloWorldRequest() {
        }
        
        public HelloWorldRequest(ASMXClient.ServiceReference1.HelloWorldRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class HelloWorldRequestBody {
        
        public HelloWorldRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class HelloWorldResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="HelloWorldResponse", Namespace="http://tempuri.org/", Order=0)]
        public ASMXClient.ServiceReference1.HelloWorldResponseBody Body;
        
        public HelloWorldResponse() {
        }
        
        public HelloWorldResponse(ASMXClient.ServiceReference1.HelloWorldResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class HelloWorldResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string HelloWorldResult;
        
        public HelloWorldResponseBody() {
        }
        
        public HelloWorldResponseBody(string HelloWorldResult) {
            this.HelloWorldResult = HelloWorldResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class SummRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="Summ", Namespace="http://tempuri.org/", Order=0)]
        public ASMXClient.ServiceReference1.SummRequestBody Body;
        
        public SummRequest() {
        }
        
        public SummRequest(ASMXClient.ServiceReference1.SummRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class SummRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string number1;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string number2;
        
        public SummRequestBody() {
        }
        
        public SummRequestBody(string number1, string number2) {
            this.number1 = number1;
            this.number2 = number2;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class SummResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="SummResponse", Namespace="http://tempuri.org/", Order=0)]
        public ASMXClient.ServiceReference1.SummResponseBody Body;
        
        public SummResponse() {
        }
        
        public SummResponse(ASMXClient.ServiceReference1.SummResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class SummResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string SummResult;
        
        public SummResponseBody() {
        }
        
        public SummResponseBody(string SummResult) {
            this.SummResult = SummResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface WebServiceSoapChannel : ASMXClient.ServiceReference1.WebServiceSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class WebServiceSoapClient : System.ServiceModel.ClientBase<ASMXClient.ServiceReference1.WebServiceSoap>, ASMXClient.ServiceReference1.WebServiceSoap {
        
        public WebServiceSoapClient() {
        }
        
        public WebServiceSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public WebServiceSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WebServiceSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WebServiceSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ASMXClient.ServiceReference1.HelloWorldResponse ASMXClient.ServiceReference1.WebServiceSoap.HelloWorld(ASMXClient.ServiceReference1.HelloWorldRequest request) {
            return base.Channel.HelloWorld(request);
        }
        
        public string HelloWorld() {
            ASMXClient.ServiceReference1.HelloWorldRequest inValue = new ASMXClient.ServiceReference1.HelloWorldRequest();
            inValue.Body = new ASMXClient.ServiceReference1.HelloWorldRequestBody();
            ASMXClient.ServiceReference1.HelloWorldResponse retVal = ((ASMXClient.ServiceReference1.WebServiceSoap)(this)).HelloWorld(inValue);
            return retVal.Body.HelloWorldResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ASMXClient.ServiceReference1.HelloWorldResponse> ASMXClient.ServiceReference1.WebServiceSoap.HelloWorldAsync(ASMXClient.ServiceReference1.HelloWorldRequest request) {
            return base.Channel.HelloWorldAsync(request);
        }
        
        public System.Threading.Tasks.Task<ASMXClient.ServiceReference1.HelloWorldResponse> HelloWorldAsync() {
            ASMXClient.ServiceReference1.HelloWorldRequest inValue = new ASMXClient.ServiceReference1.HelloWorldRequest();
            inValue.Body = new ASMXClient.ServiceReference1.HelloWorldRequestBody();
            return ((ASMXClient.ServiceReference1.WebServiceSoap)(this)).HelloWorldAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ASMXClient.ServiceReference1.SummResponse ASMXClient.ServiceReference1.WebServiceSoap.Summ(ASMXClient.ServiceReference1.SummRequest request) {
            return base.Channel.Summ(request);
        }
        
        public string Summ(string number1, string number2) {
            ASMXClient.ServiceReference1.SummRequest inValue = new ASMXClient.ServiceReference1.SummRequest();
            inValue.Body = new ASMXClient.ServiceReference1.SummRequestBody();
            inValue.Body.number1 = number1;
            inValue.Body.number2 = number2;
            ASMXClient.ServiceReference1.SummResponse retVal = ((ASMXClient.ServiceReference1.WebServiceSoap)(this)).Summ(inValue);
            return retVal.Body.SummResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ASMXClient.ServiceReference1.SummResponse> ASMXClient.ServiceReference1.WebServiceSoap.SummAsync(ASMXClient.ServiceReference1.SummRequest request) {
            return base.Channel.SummAsync(request);
        }
        
        public System.Threading.Tasks.Task<ASMXClient.ServiceReference1.SummResponse> SummAsync(string number1, string number2) {
            ASMXClient.ServiceReference1.SummRequest inValue = new ASMXClient.ServiceReference1.SummRequest();
            inValue.Body = new ASMXClient.ServiceReference1.SummRequestBody();
            inValue.Body.number1 = number1;
            inValue.Body.number2 = number2;
            return ((ASMXClient.ServiceReference1.WebServiceSoap)(this)).SummAsync(inValue);
        }
    }
}
